DATASET: COCO
DATADIR: data/COCO
NUM_WORKERS: 40
DISP_FREQ: 10
SEED: 100

CUDNN:
  BENCHMARK: False
  DETERMINISTIC: True
  ENABLE: True

MODEL:
  TYPE: FSR
DATA:
  NUM_CLASSES: 80
  LARGE_SIZE: 224
  SMALL_SIZE: 112

TRAIN:
  BATCH_SIZE: 32
  BATCH_MULTIPLY: 1
TEST:
  BATCH_SIZE: 32

KD:
  ARCH_T: 'r101'
  ARCH_S: 'r34'
  TEMP: 4
  ALPHA: 0.9
  MODELDICT_T: ckpt/COCO/BASELINE_SIZE224_SEED100/ckpt_base/model_best.pth
  SOLVER:
    START_LR: 0.001
    LR_STEPS: [30]
    NUM_EPOCHS: 50
    LR_FACTOR: 0.1
    MUMENTUM: 0.9
    WEIGHT_DECAY: 0.0005
