DATASET: COCO
DATADIR: data/COCO
NUM_WORKERS: 40
DISP_FREQ: 10
SEED: 100

CUDNN:
  BENCHMARK: False
  DETERMINISTIC: True
  ENABLE: True

MODEL:
  TYPE: BASELINE
DATA:
  NUM_CLASSES: 80
  INPUT_SIZE: 112

BASE:
  ARCH: 'r34'
  TRAIN:
    BATCH_SIZE: 16
    BATCH_MULTIPLY: 2
  TEST:
    BATCH_SIZE: 16
  SOLVER:
    START_LR: 0.001
    LR_STEPS: [30]
    NUM_EPOCHS: 50
    LR_FACTOR: 0.1
    MUMENTUM: 0.9
    WEIGHT_DECAY: 0.0005