DATASET: VOC2007
DATADIR: data/VOC2007/VOCdevkit/VOC2007
NUM_WORKERS: 20
DISP_FREQ: 10
SEED: 50

CUDNN:
  BENCHMARK: False
  DETERMINISTIC: True
  ENABLE: True

MODEL:
  TYPE: BASELINE
DATA:
  NUM_CLASSES: 20
  LARGE_SIZE: 112

BASE:
  ARCH: 'r34'
  TRAIN:
    BATCH_SIZE: 32
    BATCH_MULTIPLY: 1
  TEST:
    BATCH_SIZE: 32
  SOLVER:
    START_LR: 0.001
    LR_STEPS: [30]
    NUM_EPOCHS: 50
    LR_FACTOR: 0.1
    MUMENTUM: 0.9
    WEIGHT_DECAY: 0.0005