DATASET: COCO
DATADIR: data/COCO
NUM_WORKERS: 40
DISP_FREQ: 10
SEED: 100

CUDNN:
  BENCHMARK: False
  DETERMINISTIC: True
  ENABLE: True

MODEL:
  TYPE: BASELINE
DATA:
  NUM_CLASSES: 80
  LARGE_SIZE: 224
  SMALL_SIZE: 112

FSR:
  GROUPS: 64
  FEATURE_TRIM: [0, 1]
  IN_PLANES: 512
  OUT_PLANES: 512
  SMALL_ARCH: 'r34'

  TEST:
    BATCH_SIZE: 32
    STATE_DIR: /data1/ggy/code/FSR/ckpt/COCO/KD-FSR-2SIZE_ARCHr101-r34_SIZE224-112_SEED100