DATASET: COCO
DATADIR: data/COCO
NUM_WORKERS: 40
DISP_FREQ: 10
SEED: 100

CUDNN:
  BENCHMARK: False
  DETERMINISTIC: True
  ENABLE: True

MODEL:
  TYPE: BASELINE
DATA:
  NUM_CLASSES: 80
  INPUT_SIZE: 112

BASE:
  ARCH: 'r34'
  TEST:
    BATCH_SIZE: 32
    STATE_DIR: /data1/ggy/code/FSR/ckpt/COCO/BASELINE_r34_SIZE112_SEED100
