DATASET: VOC2007
DATADIR: data/VOC2007/VOCdevkit/VOC2007
NUM_WORKERS: 20
DISP_FREQ: 10
SEED: 50

CUDNN:
  BENCHMARK: False
  DETERMINISTIC: True
  ENABLE: True

MODEL:
  TYPE: BASELINE
DATA:
  NUM_CLASSES: 20
  INPUT_SIZE: 112

BASE:
  ARCH: 'r34'
  TEST:
    BATCH_SIZE: 16
    STATE_DIR: /data1/ggy/code/FSR/ckpt/VOC2007/BASELINE_r34_SIZE112_SEED50
    VISUAL_SEQ: 10

